## AI Assisted Verification

process of checking answers , calculations,code or findings suggested by AI tools against reliable evidence such as our actual database.

#### Basic AI verification Process:

1. As a specific or checkable question.
2. Record the AI's answer.
3. Write and run your own sql query.
4. Compare both results.
5. Record agreement or disagreement and explain the verdict.

In [48]:
import pandas as pd
columns=[
    "Question",
    "AI Answer",
    "SQL Query",
    "Verdict",
    "Resolution"
]

verification_df=pd.DataFrame(columns=columns)
verification_df

Empty DataFrame
Columns: [Question, AI Answer, SQL Query, Verdict, Resolution]
Index: []

In [49]:
import pandas as pd
import sqlite3
con = sqlite3.connect("C:\\Users\\fathi\\OneDrive\\Documents\\ojt semester3\\ipl-cricket-analytics\\data\\raw\\ipl.db")
def q(sql):
    return pd.read_sql(sql,con)

In [50]:
q('''
SELECT COUNT(DISTINCT venue_clean) AS number_of_cleaned_venues
FROM v_matches_clean;
''')

   number_of_cleaned_venues
0                        41

In [51]:
q("""SELECT COUNT(DISTINCT venue_clean) AS unique_venues
FROM v_matches_clean;""")

   unique_venues
0             41

In [52]:
verification_df.loc[len(verification_df)] = {
    "Question": "How many distinct cleaned IPL venues are there?",
    "AI Answer": "ChatGPT suggested a query using COUNT(DISTINCT venue_clean)",
    "SQL Query": "SELECT COUNT(DISTINCT venue_clean) AS distinct_venues_count FROM v_matches_clean;",
    "SQL Result": 41,
    "Verdict": "Agree - AI-generated SQL verified",
    "Resolution": "ChatGPT's query returned 41, matching our independent SQL check. The original venue column returned 59."}
verification_df

,Question,AI Answer,SQL Query,Verdict,Resolution
0,How many distinct cleaned IPL venues are there?,ChatGPT suggested a query using COUNT(DISTINCT...,SELECT COUNT(DISTINCT venue_clean) AS distinct...,Agree - AI-generated SQL verified,"ChatGPT's query returned 41, matching our inde..."

In [53]:
q(""" SELECT COUNT(*) AS matches_count
FROM matches
WHERE match_winner='Mumbai Indians';""")

   matches_count
0            155

In [54]:
q(""" SELECT COUNT(*) AS matches_count
FROM matches
WHERE match_winner='Mumbai Indians' 
AND result='win';""")

   matches_count
0            153

In [55]:
q("""SELECT COUNT(*) AS mumbai_indians_wins
FROM matches
WHERE match_winner = 'Mumbai Indians';""")

   mumbai_indians_wins
0                  155

In [56]:
q("""SELECT COUNT(*) AS mumbai_indians_wins
FROM matches
WHERE match_winner = 'Mumbai Indians'
  AND result = 'win';""")

   mumbai_indians_wins
0                  153

In [57]:
verification_df.loc[len(verification_df)] = {
    "Question": "How many times was Mumbai Indians recorded as match_winner without filtering result?",
    "AI Answer": "ChatGPT suggested SQL to count match_winner = 'Mumbai Indians'",
    "SQL Query": "SELECT COUNT(*) FROM matches WHERE match_winner = 'Mumbai Indians';",
    "SQL Result": 155,
    "Verdict": "Agree - AI SQL verified",
    "Resolution": "Our independent SQL and ChatGPT-generated SQL both returned 155."}

verification_df.loc[len(verification_df)] = {
    "Question": "How many Mumbai Indians wins have result = 'win'?",
    "AI Answer": "ChatGPT suggested SQL with match_winner = 'Mumbai Indians' AND result = 'win'",
    "SQL Query": "SELECT COUNT(*) FROM matches WHERE match_winner = 'Mumbai Indians' AND result = 'win';",
    "SQL Result": 153,
    "Verdict": "Agree - AI SQL verified",
    "Resolution": "Our independent SQL and ChatGPT-generated SQL both returned 153. The result filter excludes 2 rows."}

verification_df

,Question,AI Answer,SQL Query,Verdict,Resolution
0,How many distinct cleaned IPL venues are there?,ChatGPT suggested a query using COUNT(DISTINCT...,SELECT COUNT(DISTINCT venue_clean) AS distinct...,Agree - AI-generated SQL verified,"ChatGPT's query returned 41, matching our inde..."
1,How many times was Mumbai Indians recorded as ...,ChatGPT suggested SQL to count match_winner = ...,SELECT COUNT(*) FROM matches WHERE match_winne...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
2,How many Mumbai Indians wins have result = 'win'?,ChatGPT suggested SQL with match_winner = 'Mum...,SELECT COUNT(*) FROM matches WHERE match_winne...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...

In [58]:
q("""SELECT COUNT(*) AS count 
FROM deliveries
WHERE fielders_involved = '[None]';""")

   count
0   3908

In [59]:
q("""SELECT COUNT(*) AS none_fielders_count
FROM deliveries
WHERE fielders_involved = '[None]';""")

   none_fielders_count
0                 3908

In [60]:
verification_df.loc[len(verification_df)] = {
    "Question": "How many deliveries have the literal text '[None]' in fielders_involved?",
    "AI Answer": "ChatGPT suggested SQL using fielders_involved = '[None]'",
    "SQL Query": "SELECT COUNT(*) FROM deliveries WHERE fielders_involved = '[None]';",
    "SQL Result": 3908,
    "Verdict": "Agree - AI SQL verified",
    "Resolution": "Our independent SQL and ChatGPT-generated SQL both returned 3908. The value '[None]' is text, not SQL NULL."}

verification_df

,Question,AI Answer,SQL Query,Verdict,Resolution
0,How many distinct cleaned IPL venues are there?,ChatGPT suggested a query using COUNT(DISTINCT...,SELECT COUNT(DISTINCT venue_clean) AS distinct...,Agree - AI-generated SQL verified,"ChatGPT's query returned 41, matching our inde..."
1,How many times was Mumbai Indians recorded as ...,ChatGPT suggested SQL to count match_winner = ...,SELECT COUNT(*) FROM matches WHERE match_winne...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
2,How many Mumbai Indians wins have result = 'win'?,ChatGPT suggested SQL with match_winner = 'Mum...,SELECT COUNT(*) FROM matches WHERE match_winne...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
3,How many deliveries have the literal text '[No...,ChatGPT suggested SQL using fielders_involved ...,SELECT COUNT(*) FROM deliveries WHERE fielders...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...

In [61]:
q("""SELECT SUM(batter_runs) AS virat_kohli_runs
FROM deliveries
WHERE batter='V Kohli'
;""")

   virat_kohli_runs
0              9050

In [62]:
q("""SELECT SUM(batter_runs) AS total_runs
FROM deliveries
WHERE batter = 'V Kohli';""")

   total_runs
0        9050

In [63]:
verification_df.loc[len(verification_df)] = {
    "Question": "How many total batting runs did V Kohli score?",
    "AI Answer": "ChatGPT suggested SUM(batsman_runs) with batter = 'V Kohli'",
    "SQL Query": "SELECT SUM(batsman_runs) AS total_runs FROM deliveries WHERE batter = 'V Kohli';",
    "SQL Result": 9050,
    "Verdict": "Agree - AI SQL verified",
    "Resolution": "Our independent SQL and ChatGPT-generated SQL both returned 9050. Only batsman_runs were included, excluding extras."}

verification_df

,Question,AI Answer,SQL Query,Verdict,Resolution
0,How many distinct cleaned IPL venues are there?,ChatGPT suggested a query using COUNT(DISTINCT...,SELECT COUNT(DISTINCT venue_clean) AS distinct...,Agree - AI-generated SQL verified,"ChatGPT's query returned 41, matching our inde..."
1,How many times was Mumbai Indians recorded as ...,ChatGPT suggested SQL to count match_winner = ...,SELECT COUNT(*) FROM matches WHERE match_winne...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
2,How many Mumbai Indians wins have result = 'win'?,ChatGPT suggested SQL with match_winner = 'Mum...,SELECT COUNT(*) FROM matches WHERE match_winne...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
3,How many deliveries have the literal text '[No...,ChatGPT suggested SQL using fielders_involved ...,SELECT COUNT(*) FROM deliveries WHERE fielders...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
4,How many total batting runs did V Kohli score?,ChatGPT suggested SUM(batsman_runs) with batte...,SELECT SUM(batsman_runs) AS total_runs FROM de...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...

In [64]:
q("""
SELECT COUNT(is_wicket) AS total_wickets
FROM deliveries
WHERE bowler = 'YS Chahal'
AND wicket_kind IN (
    'caught',
    'bowled',
    'stumped',
    'lbw',
    'caught and bowled'
);
""")

   total_wickets
0            228

In [65]:
q("""SELECT COUNT(*) AS total_wickets
FROM deliveries
WHERE bowler = 'YS Chahal'
  AND is_wicket = 1
  AND wicket_kind IN (
      'caught',
      'bowled',
      'stumped',
      'lbw',
      'caught and bowled'
  );""")

   total_wickets
0            228

In [66]:
verification_df.loc[len(verification_df)] = {
    "Question": "How many bowler-credited wickets did YS Chahal take?",
    "AI Answer": "ChatGPT suggested excluding non-bowler dismissals using NOT IN",
    "SQL Query": """SELECT COUNT(*) FROM deliveries
WHERE bowler = 'YS Chahal'
AND is_wicket = 1
AND wicket_kind NOT IN
('run out', 'retired hurt', 'retired out', 'obstructing the field');""",
    "SQL Result": 228,
    "Verdict": "Agree - AI SQL verified",
    "Resolution": "Our SQL used IN for bowler-credited dismissals; ChatGPT used NOT IN to exclude non-bowler dismissals. Both returned 228 for this dataset."}

verification_df

,Question,AI Answer,SQL Query,Verdict,Resolution
0,How many distinct cleaned IPL venues are there?,ChatGPT suggested a query using COUNT(DISTINCT...,SELECT COUNT(DISTINCT venue_clean) AS distinct...,Agree - AI-generated SQL verified,"ChatGPT's query returned 41, matching our inde..."
1,How many times was Mumbai Indians recorded as ...,ChatGPT suggested SQL to count match_winner = ...,SELECT COUNT(*) FROM matches WHERE match_winne...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
2,How many Mumbai Indians wins have result = 'win'?,ChatGPT suggested SQL with match_winner = 'Mum...,SELECT COUNT(*) FROM matches WHERE match_winne...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
3,How many deliveries have the literal text '[No...,ChatGPT suggested SQL using fielders_involved ...,SELECT COUNT(*) FROM deliveries WHERE fielders...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
4,How many total batting runs did V Kohli score?,ChatGPT suggested SUM(batsman_runs) with batte...,SELECT SUM(batsman_runs) AS total_runs FROM de...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
5,How many bowler-credited wickets did YS Chahal...,ChatGPT suggested excluding non-bowler dismiss...,SELECT COUNT(*) FROM deliveries\nWHERE bowler ...,Agree - AI SQL verified,Our SQL used IN for bowler-credited dismissals...

In [67]:
q("""
SELECT bowler,
       SUM(total_runs
           - COALESCE(bye_runs, 0)
           - COALESCE(leg_bye_runs, 0)
           - COALESCE(penalty_runs, 0)
       ) AS runs_conceded,

       SUM(CASE WHEN is_wide_ball = 0
                AND is_no_ball = 0
                THEN 1 ELSE 0
           END) AS legal_balls,

       ROUND(SUM(
               total_runs
               - COALESCE(bye_runs, 0)
               - COALESCE(leg_bye_runs, 0)
               - COALESCE(penalty_runs, 0)) * 6.0 /
           NULLIF(
               SUM(CASE WHEN is_wide_ball = 0
                        AND is_no_ball = 0
                        THEN 1 ELSE 0
                   END), 0
           ), 2
       ) AS economy_rate

FROM v_deliveries_category_clean
WHERE bowler = 'A Kumble'
  AND is_super_over = 0
GROUP BY bowler;
""")

     bowler  runs_conceded  legal_balls  economy_rate
0  A Kumble           1058          965          6.58

In [68]:
q("""
SELECT
    bowler,

    SUM(
        total_runs
        - COALESCE(bye_runs, 0)
        - COALESCE(leg_bye_runs, 0)
        - COALESCE(penalty_runs, 0)
    ) AS runs_conceded,

    SUM(
        CASE
            WHEN is_wide_ball = 0
             AND is_no_ball = 0
            THEN 1
            ELSE 0
        END
    ) AS legal_balls,

    ROUND(
        SUM(
            total_runs
            - COALESCE(bye_runs, 0)
            - COALESCE(leg_bye_runs, 0)
            - COALESCE(penalty_runs, 0)
        ) * 6.0
        /
        NULLIF(
            SUM(
                CASE
                    WHEN is_wide_ball = 0
                     AND is_no_ball = 0
                    THEN 1
                    ELSE 0
                END
            ), 0
        ),
        2
    ) AS economy_rate

FROM v_deliveries_category_clean

WHERE bowler = 'A Kumble'
  AND is_super_over = 0

GROUP BY bowler;
""")

     bowler  runs_conceded  legal_balls  economy_rate
0  A Kumble           1058          965          6.58

In [69]:
verification_df.loc[len(verification_df)] = {
    "Question": "What is A Kumble's bowling economy rate?",
    "AI Answer": "ChatGPT suggested SQL using COALESCE for wide and no-ball flags.",
    "SQL Query": """SELECT bowler,
SUM(batter_runs + wide_ball_runs + no_ball_runs) AS runs_conceded,
SUM(CASE WHEN COALESCE(is_wide_ball, 0) = 0
AND COALESCE(is_no_ball, 0) = 0
THEN 1 ELSE 0 END) AS legal_balls,
ROUND(
SUM(batter_runs + wide_ball_runs + no_ball_runs) * 6.0 /
SUM(CASE WHEN COALESCE(is_wide_ball, 0) = 0
AND COALESCE(is_no_ball, 0) = 0
THEN 1 ELSE 0 END), 2
) AS economy_rate
FROM deliveries
WHERE bowler = 'A Kumble'
GROUP BY bowler;""",
    "SQL Result": 6.58,
    "Verdict": "Agree - AI SQL verified",
    "Resolution": "Both queries returned 1058 runs conceded, 965 legal balls, and an economy rate of 6.58. ChatGPT used COALESCE to handle NULL flags."}

verification_df

,Question,AI Answer,SQL Query,Verdict,Resolution
0,How many distinct cleaned IPL venues are there?,ChatGPT suggested a query using COUNT(DISTINCT...,SELECT COUNT(DISTINCT venue_clean) AS distinct...,Agree - AI-generated SQL verified,"ChatGPT's query returned 41, matching our inde..."
1,How many times was Mumbai Indians recorded as ...,ChatGPT suggested SQL to count match_winner = ...,SELECT COUNT(*) FROM matches WHERE match_winne...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
2,How many Mumbai Indians wins have result = 'win'?,ChatGPT suggested SQL with match_winner = 'Mum...,SELECT COUNT(*) FROM matches WHERE match_winne...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
3,How many deliveries have the literal text '[No...,ChatGPT suggested SQL using fielders_involved ...,SELECT COUNT(*) FROM deliveries WHERE fielders...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
4,How many total batting runs did V Kohli score?,ChatGPT suggested SUM(batsman_runs) with batte...,SELECT SUM(batsman_runs) AS total_runs FROM de...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
5,How many bowler-credited wickets did YS Chahal...,ChatGPT suggested excluding non-bowler dismiss...,SELECT COUNT(*) FROM deliveries\nWHERE bowler ...,Agree - AI SQL verified,Our SQL used IN for bowler-credited dismissals...
6,What is A Kumble's bowling economy rate?,ChatGPT suggested SQL using COALESCE for wide ...,"SELECT bowler,\nSUM(batter_runs + wide_ball_ru...",Agree - AI SQL verified,"Both queries returned 1058 runs conceded, 965 ..."

In [70]:
q("""
SELECT COUNT(*) AS chase_won_matches
FROM matches
WHERE result = 'win';
""")

   chase_won_matches
0               1187

In [71]:
verification_df.loc[len(verification_df)] = {
    "Question": "Do the five first-innings score bands sum to 1187 valid matches?",
    "AI Answer": "ChatGPT generated a band-count query but used an incorrect column name: first_innings_runs.",
    "SQL Query": """WITH match_bands AS (
SELECT m.match_id,
CASE
WHEN v.first_innings_total < 140 THEN 'Under 140'
WHEN v.first_innings_total BETWEEN 140 AND 159 THEN '140-159'
WHEN v.first_innings_total BETWEEN 160 AND 179 THEN '160-179'
WHEN v.first_innings_total BETWEEN 180 AND 199 THEN '180-199'
WHEN v.first_innings_total >= 200 THEN '200+'
END AS score_band
FROM matches m
JOIN v_match_totals v ON m.match_id = v.match_id
WHERE m.result = 'win'
)
SELECT score_band, COUNT(*) AS band_count
FROM match_bands
GROUP BY score_band;""",
    "SQL Result": "219 + 241 + 312 + 217 + 198 = 1187",
    "Verdict": "Agree after correction",
    "Resolution": "ChatGPT incorrectly assumed first_innings_runs. Schema inspection confirmed first_innings_total. After correcting the column, all five band counts matched our independent Step 3 results."}

verification_df

,Question,AI Answer,SQL Query,Verdict,Resolution
0,How many distinct cleaned IPL venues are there?,ChatGPT suggested a query using COUNT(DISTINCT...,SELECT COUNT(DISTINCT venue_clean) AS distinct...,Agree - AI-generated SQL verified,"ChatGPT's query returned 41, matching our inde..."
1,How many times was Mumbai Indians recorded as ...,ChatGPT suggested SQL to count match_winner = ...,SELECT COUNT(*) FROM matches WHERE match_winne...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
2,How many Mumbai Indians wins have result = 'win'?,ChatGPT suggested SQL with match_winner = 'Mum...,SELECT COUNT(*) FROM matches WHERE match_winne...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
3,How many deliveries have the literal text '[No...,ChatGPT suggested SQL using fielders_involved ...,SELECT COUNT(*) FROM deliveries WHERE fielders...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
4,How many total batting runs did V Kohli score?,ChatGPT suggested SUM(batsman_runs) with batte...,SELECT SUM(batsman_runs) AS total_runs FROM de...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
5,How many bowler-credited wickets did YS Chahal...,ChatGPT suggested excluding non-bowler dismiss...,SELECT COUNT(*) FROM deliveries\nWHERE bowler ...,Agree - AI SQL verified,Our SQL used IN for bowler-credited dismissals...
6,What is A Kumble's bowling economy rate?,ChatGPT suggested SQL using COALESCE for wide ...,"SELECT bowler,\nSUM(batter_runs + wide_ball_ru...",Agree - AI SQL verified,"Both queries returned 1058 runs conceded, 965 ..."
7,Do the five first-innings score bands sum to 1...,ChatGPT generated a band-count query but used ...,"WITH match_bands AS (\nSELECT m.match_id,\nCAS...",Agree after correction,ChatGPT incorrectly assumed first_innings_runs...

In [72]:
from scipy import stats

toss_test = q("""
SELECT
    COUNT(*) AS n,
    SUM(
        CASE
            WHEN toss_winner = match_winner THEN 1
            ELSE 0
        END
    ) AS k
FROM matches
WHERE result = 'win'
  AND toss_winner IS NOT NULL
  AND match_winner IS NOT NULL;
""")

n = toss_test["n"].iloc[0]
k = toss_test["k"].iloc[0]

result = stats.binomtest(
    k=k,
    n=n,
    p=0.5,
    alternative="two-sided"
)

print("P-value:", round(result.pvalue, 5))

P-value: 0.27004

In [73]:
from scipy import stats

q_result = q("""
SELECT
    COUNT(*) AS n,
    SUM(CASE
        WHEN toss_winner = match_winner THEN 1
        ELSE 0
    END) AS k
FROM matches
WHERE result = 'win'
  AND toss_winner IS NOT NULL
  AND match_winner IS NOT NULL;
""")

n = int(q_result['n'].iloc[0])
k = int(q_result['k'].iloc[0])

result = stats.binomtest(
    k=k,
    n=n,
    p=0.5,
    alternative="two-sided"
)

print(round(result.pvalue, 5))

0.27004

In [74]:
verification_df.loc[len(verification_df)] = {
    "Question": "Is the two-sided toss-winner binomial test p-value 0.2700?",
    "AI Answer": (
        "ChatGPT generated Python code using scipy.stats.binomtest "
        "with k=613, n=1187, p=0.5 and alternative='two-sided'."),
    "SQL Query": (
        "SELECT COUNT(*) AS total_matches, "
        "SUM(CASE WHEN toss_winner = match_winner THEN 1 ELSE 0 END) "
        "AS toss_winner_wins "
        "FROM matches WHERE result = 'win'; "
        "Python: binomtest(k=613, n=1187, p=0.5, alternative='two-sided')"),
    "SQL Result": (
        "613 toss-winner wins / 1187 valid matches; "
        "p-value = 0.2700389712415702 (0.2700)"),
    "Verdict": "Agree",
    "Resolution": (
        "Executed ChatGPT-generated Python code and compared its output "
        "with our independently calculated binomial test p-value. "
        "Both returned 0.2700. No correction required.")}
verification_df

,Question,AI Answer,SQL Query,Verdict,Resolution
0,How many distinct cleaned IPL venues are there?,ChatGPT suggested a query using COUNT(DISTINCT...,SELECT COUNT(DISTINCT venue_clean) AS distinct...,Agree - AI-generated SQL verified,"ChatGPT's query returned 41, matching our inde..."
1,How many times was Mumbai Indians recorded as ...,ChatGPT suggested SQL to count match_winner = ...,SELECT COUNT(*) FROM matches WHERE match_winne...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
2,How many Mumbai Indians wins have result = 'win'?,ChatGPT suggested SQL with match_winner = 'Mum...,SELECT COUNT(*) FROM matches WHERE match_winne...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
3,How many deliveries have the literal text '[No...,ChatGPT suggested SQL using fielders_involved ...,SELECT COUNT(*) FROM deliveries WHERE fielders...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
4,How many total batting runs did V Kohli score?,ChatGPT suggested SUM(batsman_runs) with batte...,SELECT SUM(batsman_runs) AS total_runs FROM de...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
5,How many bowler-credited wickets did YS Chahal...,ChatGPT suggested excluding non-bowler dismiss...,SELECT COUNT(*) FROM deliveries\nWHERE bowler ...,Agree - AI SQL verified,Our SQL used IN for bowler-credited dismissals...
6,What is A Kumble's bowling economy rate?,ChatGPT suggested SQL using COALESCE for wide ...,"SELECT bowler,\nSUM(batter_runs + wide_ball_ru...",Agree - AI SQL verified,"Both queries returned 1058 runs conceded, 965 ..."
7,Do the five first-innings score bands sum to 1...,ChatGPT generated a band-count query but used ...,"WITH match_bands AS (\nSELECT m.match_id,\nCAS...",Agree after correction,ChatGPT incorrectly assumed first_innings_runs...
8,Is the two-sided toss-winner binomial test p-v...,ChatGPT generated Python code using scipy.stat...,"SELECT COUNT(*) AS total_matches, SUM(CASE WHE...",Agree,Executed ChatGPT-generated Python code and com...

In [75]:
from scipy import stats

toss_decision_table = q("""
SELECT
    CASE
        WHEN toss_decision = 'bat' THEN 'bat'
        WHEN toss_decision = 'field' THEN 'field'
        ELSE 'unknown'
    END AS toss_decision,

    SUM(CASE
        WHEN toss_winner = match_winner THEN 1
        ELSE 0
    END) AS toss_winner_won,

    SUM(CASE
        WHEN toss_winner != match_winner THEN 1
        ELSE 0
    END) AS toss_winner_didnot_win

FROM matches_clean
WHERE result = 'win'
  AND toss_decision IN ('bat', 'field')
GROUP BY toss_decision
ORDER BY toss_decision;
""")

table = toss_decision_table[
    ["toss_winner_won", "toss_winner_didnot_win"]
].values

chi2, p, dof, expected = stats.chi2_contingency(table)

print(round(p, 4))

0.0046

In [76]:
from scipy import stats

toss_decision_table = q("""
SELECT
    CASE
        WHEN toss_decision = 'bat' THEN 'bat'
        WHEN toss_decision = 'field' THEN 'field'
    END AS toss_decision,

    SUM(CASE
        WHEN toss_winner = match_winner THEN 1
        ELSE 0
    END) AS toss_winner_won,

    SUM(CASE
        WHEN toss_winner != match_winner THEN 1
        ELSE 0
    END) AS toss_winner_didnot_win

FROM matches_clean

WHERE result = 'win'
  AND toss_decision IN ('bat', 'field')
  AND toss_winner IS NOT NULL
  AND match_winner IS NOT NULL

GROUP BY toss_decision;
""")

table = toss_decision_table[
    ['toss_winner_won', 'toss_winner_didnot_win']
].values

chi2, p, dof, expected = stats.chi2_contingency(table)

print(round(p, 4))

0.0046

In [77]:
verification_df.loc[len(verification_df)] = {
    "Question": "Is the Chi-square test p-value for toss decision and toss-winner match outcome 0.0046?",
    "AI Answer": (
        "ChatGPT generated Python code using scipy.stats.chi2_contingency "
        "on a contingency table created from matches_clean, grouped by "
        "toss_decision (bat and field), with toss_winner_won and "
        "toss_winner_didnot_win as columns."
    ),
    "SQL Query": (
        "SELECT "
        "CASE "
        "WHEN toss_decision = 'bat' THEN 'bat' "
        "WHEN toss_decision = 'field' THEN 'field' "
        "END AS toss_decision, "
        "SUM(CASE WHEN toss_winner = match_winner THEN 1 ELSE 0 END) "
        "AS toss_winner_won, "
        "SUM(CASE WHEN toss_winner != match_winner THEN 1 ELSE 0 END) "
        "AS toss_winner_didnot_win "
        "FROM matches_clean "
        "WHERE result = 'win' "
        "AND toss_decision IN ('bat', 'field') "
        "AND toss_winner IS NOT NULL "
        "AND match_winner IS NOT NULL "
        "GROUP BY toss_decision; "
        "Python: chi2_contingency(table)"
    ),
    "SQL Result": (
        "Contingency table counts and Chi-square p-value must be "
        "obtained by executing the query and Python code against the database."
    ),
    "Verdict": "Agree",
    "Resolution": (
        "Execute the ChatGPT-generated SQL and Python code, then compare "
        "the resulting p-value rounded to four decimal places with the "
        "reference value 0.0046. Update the verdict after verification."
    )
}

verification_df

,Question,AI Answer,SQL Query,Verdict,Resolution
0,How many distinct cleaned IPL venues are there?,ChatGPT suggested a query using COUNT(DISTINCT...,SELECT COUNT(DISTINCT venue_clean) AS distinct...,Agree - AI-generated SQL verified,"ChatGPT's query returned 41, matching our inde..."
1,How many times was Mumbai Indians recorded as ...,ChatGPT suggested SQL to count match_winner = ...,SELECT COUNT(*) FROM matches WHERE match_winne...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
2,How many Mumbai Indians wins have result = 'win'?,ChatGPT suggested SQL with match_winner = 'Mum...,SELECT COUNT(*) FROM matches WHERE match_winne...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
3,How many deliveries have the literal text '[No...,ChatGPT suggested SQL using fielders_involved ...,SELECT COUNT(*) FROM deliveries WHERE fielders...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
4,How many total batting runs did V Kohli score?,ChatGPT suggested SUM(batsman_runs) with batte...,SELECT SUM(batsman_runs) AS total_runs FROM de...,Agree - AI SQL verified,Our independent SQL and ChatGPT-generated SQL ...
5,How many bowler-credited wickets did YS Chahal...,ChatGPT suggested excluding non-bowler dismiss...,SELECT COUNT(*) FROM deliveries\nWHERE bowler ...,Agree - AI SQL verified,Our SQL used IN for bowler-credited dismissals...
6,What is A Kumble's bowling economy rate?,ChatGPT suggested SQL using COALESCE for wide ...,"SELECT bowler,\nSUM(batter_runs + wide_ball_ru...",Agree - AI SQL verified,"Both queries returned 1058 runs conceded, 965 ..."
7,Do the five first-innings score bands sum to 1...,ChatGPT generated a band-count query but used ...,"WITH match_bands AS (\nSELECT m.match_id,\nCAS...",Agree after correction,ChatGPT incorrectly assumed first_innings_runs...
8,Is the two-sided toss-winner binomial test p-v...,ChatGPT generated Python code using scipy.stat...,"SELECT COUNT(*) AS total_matches, SUM(CASE WHE...",Agree,Executed ChatGPT-generated Python code and com...
9,Is the Chi-square test p-value for toss decisi...,ChatGPT generated Python code using scipy.stat...,SELECT CASE WHEN toss_decision = 'bat' THEN 'b...,Agree,Execute the ChatGPT-generated SQL and Python c...

In [78]:
print("Total verification rows:",len(verification_df))

print("\nVerdict Summary:")
print(verification_df["Verdict"].value_counts())

print("\nMissing Values:")
print(verification_df.isna().sum())

Total verification rows: 10

Verdict Summary:
Verdict
Agree - AI SQL verified              6
Agree                                2
Agree - AI-generated SQL verified    1
Agree after correction               1
Name: count, dtype: int64

Missing Values:
Question      0
AI Answer     0
SQL Query     0
Verdict       0
Resolution    0
dtype: int64

In [79]:
q('''SELECT match_id, match_winner, result
FROM matches_clean
WHERE match_winner = 'Mumbai Indians' 
  AND (result != 'win' OR result IS NULL);''')

   match_id    match_winner result
0   1082625  Mumbai Indians    tie
1   1216547  Mumbai Indians    tie

In [80]:
q('''SELECT result, COUNT(*) AS total_matches
FROM matches_clean
WHERE match_winner = 'Mumbai Indians'
GROUP BY result;''')

  result  total_matches
0    tie              2
1    win            153

In [81]:
comparison_df = pd.DataFrame([{
    "Question": "Why are MI recorded wins 155 but filtered wins 153?",
    "Tool 1": "Gemini",
    "Tool 1 Answer": "Correct SQL and explanation of result filtering.",
    "Tool 2": "ChatGPT",
    "Tool 2 Answer": "Correct SQL and explanation of result filtering.",
    "Database Evidence": (
        "155 recorded MI winners; 153 with result='win'. "
        "Two excluded matches: 1082625 and 1216547, both result='tie'."),
    "Disagreement": "No disagreement. Both tools gave correct SQL and explanations.",
    "Resolution": (
        "Verified excluded rows directly in SQLite. "
        "The result='win' filter excludes two tied matches.")}])
comparison_df

,Question,Tool 1,Tool 1 Answer,Tool 2,Tool 2 Answer,Database Evidence,Disagreement,Resolution
0,Why are MI recorded wins 155 but filtered wins...,Gemini,Correct SQL and explanation of result filtering.,ChatGPT,Correct SQL and explanation of result filtering.,155 recorded MI winners; 153 with result='win'...,No disagreement. Both tools gave correct SQL a...,Verified excluded rows directly in SQLite. The...

In [82]:
q('''SELECT COUNT(*) AS total_wickets
FROM deliveries
WHERE bowler = 'YS Chahal'
  AND is_wicket = 1
  AND wicket_kind IN (
      'caught',
      'bowled',
      'stumped',
      'lbw',
      'caught and bowled'
  );''')

   total_wickets
0            228

In [83]:
q('''SELECT COUNT(*) AS total_wickets
FROM deliveries
WHERE bowler = 'YS Chahal'
  AND is_wicket = 1
  AND wicket_kind IN ('caught', 'bowled', 'stumped', 'lbw', 'caught and bowled');''')

   total_wickets
0            228

In [84]:
comparison_df.loc[len(comparison_df)] = {
    "Question": "Does the YS Chahal wicket count match between both tools?",
    "Tool 1": "Gemini",
    "Tool 1 Answer": (
        "Generated SQL to count wickets taken by YS Chahal, "
        "filtering is_wicket = 1 and including caught, bowled, "
        "stumped, lbw, and caught and bowled."
    ),
    "Tool 2": "ChatGPT",
    "Tool 2 Answer": (
        "Generated SQL using COUNT(*) with bowler = 'YS Chahal' "
        "and wicket_kind IN ('caught', 'bowled', 'stumped', "
        "'lbw', 'caught and bowled')."
    ),
    "Database Evidence": (
        "Both SQL queries returned 228 wickets. "
        "The first query includes is_wicket = 1; "
        "the second query does not."
    ),
    "Disagreement": (
        "Both tools returned the same count of 228, "
        "but the SQL queries use different filtering conditions."
    ),
    "Resolution": (
        "The outputs match at 228. However, for a fair comparison, "
        "both queries should use identical conditions, including "
        "is_wicket = 1. Execute both queries again to confirm "
        "that the results remain the same."
    )
}

comparison_df

,Question,Tool 1,Tool 1 Answer,Tool 2,Tool 2 Answer,Database Evidence,Disagreement,Resolution
0,Why are MI recorded wins 155 but filtered wins...,Gemini,Correct SQL and explanation of result filtering.,ChatGPT,Correct SQL and explanation of result filtering.,155 recorded MI winners; 153 with result='win'...,No disagreement. Both tools gave correct SQL a...,Verified excluded rows directly in SQLite. The...
1,Does the YS Chahal wicket count match between ...,Gemini,Generated SQL to count wickets taken by YS Cha...,ChatGPT,Generated SQL using COUNT(*) with bowler = 'YS...,Both SQL queries returned 228 wickets. The fir...,"Both tools returned the same count of 228, but...","The outputs match at 228. However, for a fair ..."